MODEL:
  META_ARCHITECTURE: "QANet"
  WEIGHTS: "../pretrained_models/resnet50d_ra2-464e36ba.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_vd_backbone"
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEFORM_ON_PER_STAGE: [False, False, True, True]
  QANET:
    FEATURES_ENHANCE:
      RFENAME: "NORFE"
      IN_FEATURES: ["res3", "res4", "res5"]
      NUM_CHANNELS: 256
    FEATURES_MERGING:
      IS_USING_HAM: True
    POSITION_EMBEDING:
      IS_USING: True
    QA_BRANCH:
      HIDDEN_DIM: 128
      NUM_MASKS: 100
      GROUPS: 4
      INIT_CONVS: 3
      SCALE_FACTOR: 2
  MATCHER:
    ALPHA: 0.8
    DYNAMIC_K: False
    START_K: 5
  INFERENCE:
    OBJ_THRESHOLD: 0.005
    MASK_THRESHOLD: 0.45
    MAX_DETECTIONS: 100
DATASETS:
  TRAIN: ("cod10k_train",)
  TEST:  ("cod10k_test", "nc4k_test")
SOLVER:
  IMS_PER_BATCH: 2
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00025
  BACKBONE_MULTIPLIER: 1.0
  STEPS: (40000, 60000, 80000)
  MAX_ITER: 90000
  WEIGHT_DECAY: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  RANDOM_FLIP: "none"
  FORMAT: "RGB"
  MASK_FORMAT: "bitmask"
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 0
VERSION: 2
OUTPUT_DIR: '../output'
#SEED: 30665215