MODEL:
  META_ARCHITECTURE: "QANet"
  WEIGHTS: ""
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  QANET:
    FEATURES_ENHANCE:
      RFENAME: "ASPP"
      IN_FEATURES: ["res3", "res4", "res5"]
      NUM_CHANNELS: 256
    FEATURES_MERGING:
      IS_USING_HAM: True
  DECODER:
    HIDDEN_DIM: 128
    NUM_MASKS: 100
    GROUPS: 4
    SCALE_FACTOR: 2
DATASETS:
  TRAIN: ("cod10k_train",)
  TEST:  ("cod10k_test", "nc4k_test")
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.00005
  STEPS: (40000, 60000, 80000)
  MAX_ITER: 90000
  WEIGHT_DECAY: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  FORMAT: "RGB"
  MASK_FORMAT: "bitmask"
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 0
VERSION: 2
OUTPUT_DIR: 'output'
