MODEL:
  META_ARCHITECTURE: "QANet"
  WEIGHTS: ""
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  QANET:
    FEATURES_ENHANCE:
      RFENAME: "PPM"
      IN_FEATURES: ["res3", "res4", "res5"]
      NUM_CHANNELS: 256
    FEATURES_MERGING:
      IS_USING_HAM: True
    POSITION_EMBEDING:
      IS_USING: True
    QA_BRANCH:
      HIDDEN_DIM: 128
      NUM_MASKS: 100
      GROUPS: 4
      SCALE_FACTOR: 2
      DROP_RATE: 0.1
      NUM_MSCA_BLOCKS: 3
      MLP_RATIO: 4.
  MATCHER:
    ALPHA: 0.7
    BETA: 0.2
    GAMA: 0.1
  CRITERION:
    ITEMS: ("masks", "edges", "obj")
    LOSS_MASKS_DICE_WEIGHT: 1.0
    LOSS_MASKS_BCE_WEIGHT: 1.0
    LOSS_EDGES_DICE_WEIGHT: 0.2
    LOSS_EDGES_BCE_WEIGHT: 0.2
    LOSS_OBJ_WEIGHT: 1.0
    LOSS_EPRS_WEIGHT: 0.2
  INFERENCE:
    OBJ_THRESHOLD: 0.005
    MASK_THRESHOLD: 0.45
    MAX_DETECTIONS: 100
DATASETS:
  TRAIN: ("cod10k_train",)
  TEST:  ("cod10k_test", "nc4k_test")
SOLVER:
  IMS_PER_BATCH: 1
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00005
  BACKBONE_MULTIPLIER: 1.0
  STEPS: (40000, 60000, 80000)
  MAX_ITER: 90000
  WEIGHT_DECAY: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  RANDOM_FLIP: "horizontal"
  FORMAT: "RGB"
  MASK_FORMAT: "bitmask"
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 0
VERSION: 2
OUTPUT_DIR: '../output'
